### ISSUE TITLE
Bug: When clicking on "overlay" the map zooms in a random place in the east african ocean. Should use a bounding box of the gcp points + a zoom out

### ISSUE THREAD

**Issue by fredrikmoger** [TheAtlasRepository/ImgPDF2Map#117]
See title. 

Would consider this a as a critical fix.

**Comment by Trivinyx** [comment]
We are looking into this. The cause is that we allowed access to overlay, before you one got the bounding cordinates from the backend ;)

**Comment by fredrikmoger** [comment]
Konge!
